server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    client_body_temp_path /dev/shm/nginx/client_temp;
    proxy_temp_path /dev/shm/nginx/proxy_temp;
    fastcgi_temp_path /dev/shm/nginx/fastcgi_temp;
    uwsgi_temp_path /dev/shm/nginx/uwsgi_temp;
    scgi_temp_path /dev/shm/nginx/scgi_temp;
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
